version: '3'
services:
  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
      PGDATA: /var/lib/postgresql/data
    restart: always
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/books
    depends_on:
      - db
    restart: always
